export const SET_LOCATION_PHOTO: "SET_LOCATION_PHOTO" = "SET_LOCATION_PHOTO";
export const SET_GARBAGE_LOCATION: "SET_GARBAGE_LOCATION" =
  "SET_GARBAGE_LOCATION";
export const SET_GARBAGE_LOCATION_ADDRESS: "SET_GARBAGE_LOCATION_ADDRESS" =
  "SET_GARBAGE_LOCATION_ADDRESS";



